---
- name: generate hosts file
  hosts: all
  become: true
  tasks:
    - name: generating myhosts file
      template:
        src: /home/student/playbooks/hosts.j2
        dest: /etc/myhosts
      when: inventory_hostname in groups['dev']
