---
- name: Modify file
  hosts: all
  become: true
  tasks:
    - name: Development
      copy:
        content: Development
        dest: /etc/issue
      when: inventory_hostname in groups['dev']

    - name: Test
      copy:
        content: Test
        dest: /etc/issue
      when: inventory_hostname in groups['test']
    - name: Production
      copy:
        content: Production
        dest: /etc/issue
      when: inventory_hostname in groups['prod']

