---
- name: install package
  hosts: all
  become: true
  tasks:
    - name: php & mariadb
      yum:
        name:
          - php
          - mariadb
        state: latest
      when:
        - inventory_hostname in groups['dev'] or inventory_hostname in groups['test'] or inventory_hostname in groups['prod']

    - name: Development tools
      yum:
        name: "@Development Tools"
        state: latest
      when: inventory_hostname in groups['dev']

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      when: inventory_hostname in groups['dev']

